---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app n8n
  namespace: flux-system
spec:
  releaseName: *app
  targetNamespace: n8n
  interval: 10m

  chart:
    spec:
      chart: n8n
      version: 0.25.2
      sourceRef:
        kind: HelmRepository
        name: 8gears
        namespace: flux-system

  values:
    image:
      tag: 1.53.2

    config:
      executions:
        pruneData: "true"
        pruneDataMaxAge: 3760

    persistence:
      enabled: true
      type: dynamic
      storageClass: "longhorn"
      accessModes:
        - ReadWriteMany
      size: 5Gi

    replicaCount: 1

    deploymentStrategy:
      type: "Recreate"

    ingress:
      enabled: true

      annotations:
        kubernetes.io/ingress.class: "nginx"
        external-dns.alpha.kubernetes.io/target: "psalkowski.pl"
        external-dns.alpha.kubernetes.io/hostname: &host "n8n.psalkowski.pl"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"

      className: "nginx"

      hosts:
        - host: *host
          paths:
            - /rest/oauth2-credential/callback
            - /webhook-test
            - /webhook

      tls:
        - hosts:
            - *host
          secretName: "n8n.psalkowski.pl-tls"

    extraEnv:
      N8N_EMAIL_MODE: "smtp"
      N8N_SMTP_HOST: "smtp.eu.mailgun.org"
      N8N_SMTP_PORT: "587"
      N8N_SMTP_SENDER: "system@psalkowski.pl"
      N8N_SMTP_SSL: "false"
      N8N_BASIC_AUTH_ACTIVE: "false"
      N8N_LOG_OUTPUT: "console"
      N8N_DIAGNOSTICS_ENABLED: "false"
      WEBHOOK_URL: "https://n8n.psalkowski.pl"
      TZ: "Europe/Warsaw"
      GENERIC_TIMEZONE: "Europe/Warsaw"

    extraEnvSecrets:
      N8N_SMTP_USER:
        name: n8n-smtp
        key: username
      N8N_SMTP_PASS:
        name: n8n-smtp
        key: password
