---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: flux-system
spec:
  releaseName: *app
  targetNamespace: home-assistant
  interval: 10m

  chart:
    spec:
      chart: home-assistant
      version: 0.2.81
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: flux-system

  values:
    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: 5Gi

    hostNetwork: false

    configuration:
      enabled: true
      forceInit: false
      templateConfig: |-
        # Loads default set of integrations. Do not remove.
        default_config:
    
        {{- if .Values.ingress.enabled }}
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            {{- range .Values.configuration.trusted_proxies }}
            - {{ . }}
            {{- end }}
        {{- end}}
        # Load frontend themes from the themes folder
        frontend:
          themes: !include_dir_merge_named themes
    
        automation: !include automations.yaml
        script: !include scripts.yaml
        scene: !include scenes.yaml
        sensor: !include sensors.yaml
        template: !include templates.yaml

    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/target: "psalkowski.pl"
        external-dns.alpha.kubernetes.io/hostname: &host "ha.psalkowski.pl"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: home-assistant-tls
          hosts:
            - *host

    addons:
      codeserver:
        enabled: true
        service:
          type: LoadBalancer

    service:
      type: ClusterIP
      port: 8123

    nodeSelector:
      support/zigbee: "true"

    additionalVolumes:
      - hostPath:
          path: >-
            /run/dbus
          type: Directory
        name: dbus
      - hostPath:
          path: >-
            /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20240104094717-if00
          type: CharDevice
        name: usb

    additionalMounts:
      - mountPath: /run/dbus
        name: dbus
        readOnly: true
      - mountPath: /dev/ttyACM0
        name: usb

    securityContext:
      privileged: true
