---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app nexus
  namespace: flux-system
spec:
  releaseName: *app
  targetNamespace: nexus
  interval: 1m

  chart:
    spec:
      chart: nxrm-ha
      version: 71.0.0
      sourceRef:
        kind: HelmRepository
        name: sonatype
        namespace: flux-system

  values:
    nameOverride: nexus

    namespaces:
      nexusNs:
        enabled: false
        name: nexus

    nexus:
      docker:
        enabled: true
        type: ClusterIP
        registries:
          - port: 8082
            targetPort: 8082
            host: docker.psalkowski.pl
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-production"
              external-dns.alpha.kubernetes.io/hostname: "docker.psalkowski.pl"
            secretName: docker.psalkowski.pl-tls

    statefulset:
      clustered: false

      nodeSelector:
        role: master

    service:
      nexus:
        enabled: true
        type: ClusterIP
        protocol: TCP
        port: 80
        targetPort: 8081

    ingress:
      enabled: true
      host: nexus.psalkowski.pl
      ingressClassName: nginx
      defaultRule: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/hostname: "nexus.psalkowski.pl"
      tls:
        - hosts:
            - nexus.psalkowski.pl
          secretName: nexus.psalkowski.pl-tls

    secret:
      dbSecret:
        enabled: false

      nexusAdminSecret:
        enabled: false

      nexusAdmin:
        name: "admin"

  # Remove license file, so we can use OSS version of Nexus
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: StatefulSet
              name: nexus
            patch: |-
              kind: StatefulSet
              metadata:
                name: nexus
              spec:
                template:
                  spec:
                    containers:
                      - env:
                          - name: INSTALL4J_ADD_VM_PARAMS
                            value: -Xms2703m -Xmx2703m -Dnexus.datastore.enabled=true
                              -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs -Dnexus.datastore.nexus.jdbcUrl=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
                              -Dnexus.datastore.nexus.username=${DB_USER} -Dnexus.datastore.nexus.password=${DB_PASSWORD}
                        name: nxrm-app
